# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", type: "dhcp"

  config.vm.define "web", primary:true do |web|
    web.vm.box = "ubuntu/bionic64"
    web.vm.hostname = "nodeex1"
    web.vm.provision "shell", path: "provision.sh"
    web.vm.synced_folder '.', '/vagrant', disabled: true
    web.vm.synced_folder "sites-enabled", "/vagrant/sites-enabled"
    web.vm.network "forwarded_port", guest: 8080, host: 8080, id: "nginx", host_ip: "127.0.0.1"
  end

  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/bionic64"
    db.vm.hostname = "nodeex2"
    db.vm.provision "shell", path: "provision1.sh"
    db.vm.synced_folder '.', '/vagrant', disabled: true
    db.vm.synced_folder "sites-enabled", "/vagrant/sites-enabled"
  end
end
